//! Dioxus Web Dashboard - Compiles into the 4.2 MB binary
//!
//! Reactive web UI using Dioxus framework.
//! No separate build step, no node_modules.

use axum::{
    http::header,
    response::IntoResponse,
};

/// Serve the dashboard SPA
pub async fn serve_dashboard() -> impl IntoResponse {
    // Dioxus compiles the dashboard into static HTML/JS at build time
    // This is the embedded index.html
    (
        [(header::CONTENT_TYPE, "text/html; charset=utf-8")],
        DASHBOARD_HTML,
    )
}

/// Serve embedded assets (CSS, JS)
pub async fn serve_assets(path: axum::extract::Path<String>) -> impl IntoResponse {
    let path = path.0;
    
    match path.as_str() {
        "dashboard.css" => (
            [(header::CONTENT_TYPE, "text/css; charset=utf-8")],
            DASHBOARD_CSS,
        ).into_response(),
        "dashboard.js" => (
            [(header::CONTENT_TYPE, "application/javascript; charset=utf-8")],
            DASHBOARD_JS,
        ).into_response(),
        _ => (axum::http::StatusCode::NOT_FOUND, "Not found").into_response(),
    }
}

// Embedded static files (in production, generated by Dioxus)
const DASHBOARD_HTML: &str = r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SuperInstance Ranch</title>
    <link rel="stylesheet" href="/assets/dashboard.css">
</head>
<body>
    <div id="app">
        <div class="dashboard">
            <header class="dashboard-header">
                <h1>🐄 SuperInstance Ranch</h1>
                <span class="day-counter" id="day-counter">Day 14</span>
            </header>
            
            <div class="dashboard-grid">
                <section class="panel species-panel">
                    <h2>Species</h2>
                    <ul class="species-list" id="species-list">
                        <li class="species-item">
                            <span class="species-name">🐄 Cattle</span>
                            <span class="species-count">x2</span>
                            <span class="species-status status-ACTIVE">ACTIVE</span>
                        </li>
                        <li class="species-item">
                            <span class="species-name">🐑 Sheep</span>
                            <span class="species-count">x5</span>
                            <span class="species-status status-ACTIVE">ACTIVE</span>
                        </li>
                        <li class="species-item">
                            <span class="species-name">🦆 Duck</span>
                            <span class="species-count">x3</span>
                            <span class="species-status status-ACTIVE">ACTIVE</span>
                        </li>
                        <li class="species-item">
                            <span class="species-name">🐐 Goat</span>
                            <span class="species-count">x2</span>
                            <span class="species-status status-ACTIVE">ACTIVE</span>
                        </li>
                        <li class="species-item">
                            <span class="species-name">🐗 Hog</span>
                            <span class="species-count">x1</span>
                            <span class="species-status status-ACTIVE">ACTIVE</span>
                        </li>
                        <li class="species-item">
                            <span class="species-name">🐔 Chicken</span>
                            <span class="species-count">x3</span>
                            <span class="species-status status-ACTIVE">ACTIVE</span>
                        </li>
                        <li class="species-item">
                            <span class="species-name">🐎 Horse</span>
                            <span class="species-count">x1</span>
                            <span class="species-status status-IDLE">IDLE</span>
                        </li>
                    </ul>
                </section>
                
                <section class="panel resource-panel">
                    <h2>Resources</h2>
                    <div class="gauges">
                        <div class="gauge">
                            <label>GPU Memory</label>
                            <div class="gauge-bar">
                                <div class="gauge-fill" style="width: 45%;"></div>
                            </div>
                            <span id="vram">2.9GB / 6.5GB</span>
                        </div>
                        <div class="gauge">
                            <label>CPU</label>
                            <div class="gauge-bar">
                                <div class="gauge-fill" style="width: 28%;"></div>
                            </div>
                            <span id="cpu">28%</span>
                        </div>
                        <div class="gauge">
                            <label>RAM</label>
                            <div class="gauge-bar">
                                <div class="gauge-fill" style="width: 40%;"></div>
                            </div>
                            <span id="ram">3.2GB</span>
                        </div>
                    </div>
                    <div class="savings">
                        <strong>💰 Saved: $<span id="savings">127.50</span></strong>
                        <span><span id="cloud-calls">255</span> cloud calls avoided</span>
                    </div>
                </section>
                
                <section class="panel activity-panel">
                    <h2>Activity</h2>
                    <ul class="activity-list" id="activity-log">
                        <li class="activity-item">
                            <span class="activity-time">10:23</span>
                            <span class="activity-emoji">🐔</span>
                            <span class="activity-msg">Motion detected (perimeter)</span>
                        </li>
                        <li class="activity-item">
                            <span class="activity-time">10:22</span>
                            <span class="activity-emoji">🦆</span>
                            <span class="activity-msg">Fetched calendar data</span>
                        </li>
                        <li class="activity-item">
                            <span class="activity-time">10:20</span>
                            <span class="activity-emoji">🐑</span>
                            <span class="activity-msg">Consensus: 4 spam, 12 good</span>
                        </li>
                        <li class="activity-item">
                            <span class="activity-time">10:18</span>
                            <span class="activity-emoji">🐐</span>
                            <span class="activity-msg">Navigated /var/log/syslog</span>
                        </li>
                        <li class="activity-item">
                            <span class="activity-time">10:15</span>
                            <span class="activity-emoji">🐄</span>
                            <span class="activity-msg">Briefing generated</span>
                        </li>
                    </ul>
                </section>
                
                <section class="panel actions-panel">
                    <h2>Actions</h2>
                    <div class="quick-actions">
                        <button class="action-btn" onclick="triggerAction('morning-routine')">[D] Morning Routine</button>
                        <button class="action-btn" onclick="triggerAction('night-school')">[N] Night School</button>
                        <button class="action-btn" onclick="triggerAction('create-breed')">[B] Create Breed</button>
                        <button class="action-btn danger" onclick="triggerAction('quit')">[Q] Quit</button>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <script src="/assets/dashboard.js"></script>
</body>
</html>
"#;

const DASHBOARD_CSS: &str = r#"
:root {
    --bg-primary: #1a1a2e;
    --bg-secondary: #16213e;
    --text-primary: #eee;
    --text-secondary: #888;
    --accent: #e94560;
    --success: #4ade80;
    --warning: #fbbf24;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
    font-family: 'JetBrains Mono', 'Fira Code', monospace;
    background: var(--bg-primary);
    color: var(--text-primary);
    min-height: 100vh;
}

.dashboard {
    display: grid;
    grid-template-rows: auto 1fr;
    min-height: 100vh;
    padding: 1rem;
}

.dashboard-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1rem;
    border-bottom: 1px solid var(--bg-secondary);
}

.day-counter {
    background: var(--accent);
    padding: 0.5rem 1rem;
    border-radius: 4px;
}

.dashboard-grid {
    display: grid;
    grid-template-columns: 1fr 300px;
    grid-template-rows: auto 1fr;
    gap: 1rem;
    padding: 1rem 0;
}

.panel {
    background: var(--bg-secondary);
    border-radius: 8px;
    padding: 1rem;
}

.panel h2 {
    font-size: 0.875rem;
    text-transform: uppercase;
    color: var(--text-secondary);
    margin-bottom: 1rem;
}

.species-list { list-style: none; }
.species-item {
    display: flex;
    justify-content: space-between;
    padding: 0.5rem 0;
    border-bottom: 1px solid rgba(255,255,255,0.1);
}

.gauge { margin: 0.5rem 0; }
.gauge-bar {
    background: rgba(255,255,255,0.1);
    height: 8px;
    border-radius: 4px;
    margin: 0.5rem 0;
}
.gauge-fill {
    background: var(--success);
    height: 100%;
    border-radius: 4px;
}

.savings {
    margin-top: 1.5rem;
    padding-top: 1rem;
    border-top: 1px solid rgba(255,255,255,0.1);
    text-align: center;
}

.activity-list { list-style: none; }
.activity-item {
    display: flex;
    gap: 0.5rem;
    padding: 0.25rem 0;
    font-size: 0.875rem;
}

.quick-actions {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
}
.action-btn {
    background: rgba(255,255,255,0.1);
    border: none;
    color: var(--text-primary);
    padding: 0.75rem;
    border-radius: 4px;
    cursor: pointer;
    text-align: left;
    font-family: inherit;
}
.action-btn:hover { background: rgba(255,255,255,0.2); }
.action-btn.danger { color: var(--accent); }

.status-ACTIVE { color: var(--success); }
.status-IDLE { color: var(--warning); }

@media (max-width: 768px) {
    .dashboard-grid {
        grid-template-columns: 1fr;
    }
}
"#;

const DASHBOARD_JS: &str = r#"
// SuperInstance Dashboard - Minimal reactive layer
// Connects to WebSocket for real-time updates

let ws;

function connectWebSocket() {
    ws = new WebSocket(`ws://${location.host}/ws`);

    ws.onopen = () => {
        console.log('🟢 Connected to Ranch');
        requestStatus();
    };

    ws.onclose = () => {
        console.log('🔴 Disconnected from Ranch');
        setTimeout(connectWebSocket, 3000);
    };

    ws.onmessage = (event) => {
        try {
            const data = JSON.parse(event.data);
            updateDashboard(data);
        } catch (e) {
            console.log('Message:', event.data);
        }
    };
}

function requestStatus() {
    if (ws && ws.readyState === WebSocket.OPEN) {
        ws.send('status');
    }
}

function updateDashboard(data) {
    console.log('Ranch status:', data);
    if (data.day !== undefined) {
        document.getElementById('day-counter').textContent = `Day ${data.day}`;
    }
    if (data.money_saved !== undefined) {
        document.getElementById('savings').textContent = data.money_saved.toFixed(2);
    }
    if (data.cloud_calls_avoided !== undefined) {
        document.getElementById('cloud-calls').textContent = data.cloud_calls_avoided;
    }
}

// Keyboard shortcuts
document.addEventListener('keydown', (e) => {
    // Don't trigger if typing in an input
    if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') return;
    
    switch(e.key.toLowerCase()) {
        case 'd': triggerAction('morning-routine'); break;
        case 'n': triggerAction('night-school'); break;
        case 'b': triggerAction('create-breed'); break;
        case 'q': triggerAction('quit'); break;
    }
});

async function triggerAction(action) {
    try {
        const res = await fetch(`/api/${action}`, { method: 'POST' });
        const data = await res.json();
        console.log('Action result:', data);
        requestStatus();
    } catch (e) {
        console.error('Action failed:', e);
    }
}

// Start connection
connectWebSocket();

// Periodic status updates
setInterval(requestStatus, 5000);
"#;
